-- Create extensions
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;
CREATE EXTENSION IF NOT EXISTS postgis_raster;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;
CREATE EXTENSION IF NOT EXISTS vector;

-- Install pg_graphql
CREATE EXTENSION IF NOT EXISTS pg_graphql;

-- Install postgis
CREATE EXTENSION IF NOT EXISTS postgis;


-- Authentication and JWT
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pgjwt;

-- Omni extensions
CREATE EXTENSION IF NOT EXISTS omni_types CASCADE;
CREATE EXTENSION IF NOT EXISTS omni_httpd CASCADE;
CREATE EXTENSION IF NOT EXISTS omni_vfs CASCADE;
CREATE EXTENSION IF NOT EXISTS omni_mimetypes CASCADE;

-- AI extensions
CREATE EXTENSION plpython3u;
CREATE EXTENSION ai;
